# Generated by Django 4.1 on 2022-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="best_record2",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
