# Generated by Django 4.1 on 2022-08-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("op1", models.CharField(max_length=50)),
                ("op2", models.CharField(max_length=50)),
                ("op3", models.CharField(max_length=50)),
                ("op4", models.CharField(max_length=50)),
            ],
        ),
    ]
