# Generated by Django 4.1 on 2022-08-26 15:28

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.IntegerField(default=Home.models.random_answer),
        ),
    ]
