# Generated by Django 4.1 on 2022-08-26 15:31

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(default=Home.models.random_answer, max_length=50),
        ),
    ]
