# Generated by Django 4.1 on 2022-08-30 16:04

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_alter_question_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionCapital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("op1", models.CharField(max_length=50)),
                ("op2", models.CharField(max_length=50)),
                ("op3", models.CharField(max_length=50)),
                ("op4", models.CharField(max_length=50)),
                ("answer", models.IntegerField(default=Home.models.random_answer)),
            ],
        ),
    ]
